# This is a basic workflow to help you get started with Actions
name: CI Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - feature/*
    - feature/*/*
    - bugfix/*
    - hotfix/*
  pull_request:
    branches: 
      - develop
      - feature/*
      - feature/*/*
      - master
      - bugfix/*
      - hotfix/*
        - 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test:
      name: Run Unit Test
      runs-on: macOS-latest
      strategy:
        matrix:
          devices: ["iPhone 8 (11.4)"] 
      steps:
        - name: Installing iOS Simulators
          run: |
            hostname
            ls /Applications | grep 'Xc'
            sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
            ls /Applications/Xcode_11.6.app/
            ls /Applications/Xcode_11.6.0.app/
            ls /Applications/Xcode_11.6.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/
            ls /Applications/Xcode_11.6.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Runtimes/iOS.simruntime/Contents
            xcrun simctl list runtimes
            xcrun simctl list devicetypes
